### ISSUE TITLE
A warning regarding await keyword

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx-hare#1722] opened 2021-07-27 15:22 UTC
I see the following warning during `make`:
```
test/test_delivery_herald.py:51
  /w/hare/hax/test/test_delivery_herald.py:51: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7
    def await(self):
```

**Comment by cortx-admin** [comment] 2021-11-12 16:24
> Justin Woo commented in Jira Server:

[~534380] is this going to be scheduled in an upcoming sprint? 

Is it going to be fixed or scheduled on the backlog?

We are updating issues in Github and want it to reflect the current status.

**Comment by cortx-admin** [comment] 2022-01-13 11:46
> Shreya Karmakar commented in Jira Server:

{code:java}
DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7 {code}

This warning tells us that in updated versions of python, *await* and *async* will be treated as keywords. And hence we get this warning while reusing in the user-defined functions and variables.

Solution:
Rename the function names from await to anything relevant.

**Comment by cortx-admin** [comment] 2022-01-20 18:01
> Pavan Krishna Thunuguntla commented in Jira Server:

Created PR

**Comment by supriyachavan4398** [comment] 2022-01-21 10:10
@max-seagate, This warning got resolved in this PR: https://github.com/Seagate/cortx-hare/pull/1948, please check.
Since the issue is resolved, Is it okay to close the issue?

**Closed** 2022-01-21 10:31 UTC
Labels: needs-triage, Status: L2 Triage, Triage:DevTeam, Justin

**Comment by cortx-admin** [comment] 2022-01-21 10:34
> Supriya Chavan commented in Jira Server:

Merged to main.

**Comment by cortx-admin** [comment] 2022-01-21 10:34
> Supriya Chavan commented in Jira Server:

Verified
