### ISSUE TITLE
"filesystem-stats:" returning empty in case of single node RGW-MOTR deployment 

### ISSUE THREAD

**Issue by rajeshdesh** [Seagate/cortx-hare#1968] opened 2022-02-02 12:49 UTC
I have 2 instances of single node RGW-MOTR deployments, deployed at different times. On second deployment I am noticing that `hctl status --json` is returning empty dictionary whereas same is working fine on older deployment.

From system its returning empty
```
[root@sm19-r19 ~]# rpm -qa | grep cortx-hare
cortx-hare-debuginfo-2.0.0-1_gitb617d08.el8.x86_64
cortx-hare-2.0.0-1_gitb617d08.el8.x86_64
[root@sm19-r19 ~]#
[root@sm19-r19 ~]#
[root@sm19-r19 ~]# rpm -qa | grep cortx-motr
cortx-motr-2.0.0-1_git6d6c31c8_any.el8.x86_64
cortx-motr-debuginfo-2.0.0-1_git6d6c31c8_any.el8.x86_64
cortx-motr-devel-2.0.0-1_git6d6c31c8_any.el8.x86_64
[root@sm19-r19 ~]#
[root@sm19-r19 ~]#
[root@sm19-r19 ~]# hctl status --json
{
  "byte_count": [
    {
      "critical_byte_count": 0,
      "damaged_byte_count": 0,
      "degraded_byte_count": 0,
      "healthy_byte_count": 0
    }
  ],
  "pools": [
    {
      "fid": "0x6f00000000000001:0x2b",
      "name": "the pool"
    }
  ],
  "profiles": [
    {
      "fid": "0x7000000000000001:0x46",
      "name": "default",
      "pools": [
        "the pool",
        null,
        null
      ]
    }
  ],
  "filesystem": {
    "stats": {}
  },
  "nodes": [
    {
      "name": "sm19-r19.pun.seagate.com",
      "svcs": [
        {
          "name": "hax",
          "fid": "0x7200000000000001:0x6",
          "ep": "inet:tcp:172.19.100.122@2001",
          "status": "started"
        },
        {
          "name": "confd",
          "fid": "0x7200000000000001:0x9",
          "ep": "inet:tcp:172.19.100.122@3001",
          "status": "started"
        },
        {
          "name": "ioservice",
          "fid": "0x7200000000000001:0xc",
          "ep": "inet:tcp:172.19.100.122@3002",
          "status": "started"
        },
        {
          "name": "m0_client",
          "fid": "0x7200000000000001:0x25",
          "ep": "inet:tcp:172.19.100.122@5001",
          "status": "started"
        },
        {
          "name": "m0_client",
          "fid": "0x7200000000000001:0x28",
          "ep": "inet:tcp:172.19.100.122@5002",
          "status": "unknown"
        }
      ]
    }
  ]
}
[root@sm19-r19 ~]#
[root@sm19-r19 ~]# hctl status
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x2b 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x46 'default': 'the pool' None None
Services:
    sm19-r19.pun.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:172.19.100.122@2001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:172.19.100.122@3001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:172.19.100.122@3002
    [started]  m0_client  0x7200000000000001:0x25  inet:tcp:172.19.100.122@5001
    [unknown]  m0_client  0x7200000000000001:0x28  inet:tcp:172.19.100.122@5002
[root@sm19-r19 ~]#
```
From system its returning fine
```
[root@sm18-r19 ~]# rpm -qa | grep cortx-hare
cortx-hare-debuginfo-2.0.0-1_git6586403.el8.x86_64
cortx-hare-2.0.0-1_git6586403.el8.x86_64
[root@sm18-r19 ~]#
[root@sm18-r19 ~]#
[root@sm18-r19 ~]# rpm -qa | grep cortx-motr
cortx-motr-debuginfo-2.0.0-1_gitbc3a79da_any.el8.x86_64
cortx-motr-devel-2.0.0-1_gitbc3a79da_any.el8.x86_64
cortx-motr-2.0.0-1_gitbc3a79da_any.el8.x86_64
[root@sm18-r19 ~]#
[root@sm18-r19 ~]# hctl status --json | grep disk
      "fs_free_disk": 318455218700288,
      "fs_avail_disk": 318455218700288,
      "fs_total_disk": 318858372055040,
[root@sm18-r19 ~]#
```

**Comment by cortx-admin** [comment] 2022-02-02 12:51
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28473. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by justinzw** [comment] 2022-02-19 16:48
@rajeshdesh I want to work on reproducing this issue. What instructions are you following?

**Comment by cortx-admin** [comment] 2022-02-28 05:06
> Rajesh Deshmukh commented in Jira Server:

Hi [~752700], I had followed PRIVATE page for deploying single node MGW instance.
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/808583540/Motr+RGW+MGW+on+single-node+HOWTO

The system is still available if you want to check live
hostname: sm19-r19.pun.seagate.com / root / seagate1
{noformat}
[root@sm19-r19 ~]# hctl status
Byte_count:
    critical_byte_count : 0
    damaged_byte_count : 0
    degraded_byte_count : 0
    healthy_byte_count : 0
Data pool:
    # fid name
    0x6f00000000000001:0x2b 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x46 'default': 'the pool' None None
Services:
    sm19-r19.pun.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   inet:tcp:172.19.100.122@2001
    [started]  confd      0x7200000000000001:0x9   inet:tcp:172.19.100.122@3001
    [started]  ioservice  0x7200000000000001:0xc   inet:tcp:172.19.100.122@3002
    [started]  m0_client  0x7200000000000001:0x25  inet:tcp:172.19.100.122@5001
    [unknown]  m0_client  0x7200000000000001:0x28  inet:tcp:172.19.100.122@5002
[root@sm19-r19 ~]#
[root@sm19-r19 ~]#
[root@sm19-r19 ~]# hctl status --json | grep disk
[root@sm19-r19 ~]#
{noformat}

**Comment by vaibhavparatwar** [comment] 2022-03-28 08:08
@rajeshdesh this is not supported on the build which you are using it seems. So closing this. File system stats are not supported. Now with dg_bytecount changes merged, we support degraded bytecount. Closing this for now

**Closed by vaibhavparatwar** 2022-03-28 08:08 UTC
Labels: needs-attention

**Comment by cortx-admin** [comment] 2022-03-28 09:16
> Vaibhav Prakash Paratwar commented in Jira Server:

This ws not supported on the build it was tested. so closing it.

**Comment by cortx-admin** [comment] 2022-03-28 09:16
> Vaibhav Prakash Paratwar commented in Jira Server:

Not supported on the build where it was reported

**Comment by cortx-admin** [comment] 2022-03-28 09:16
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment] 2022-03-28 09:16
> Vaibhav Prakash Paratwar commented in Jira Server:

.
